// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match_service_model.proto

package com.chesshouzs.server.service.rpc.pb;

public final class MatchServiceModel {
  private MatchServiceModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidateMoveReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ValidateMoveReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string oldState = 1;</code>
     * @return The oldState.
     */
    java.lang.String getOldState();
    /**
     * <code>string oldState = 1;</code>
     * @return The bytes for oldState.
     */
    com.google.protobuf.ByteString
        getOldStateBytes();

    /**
     * <code>string newState = 2;</code>
     * @return The newState.
     */
    java.lang.String getNewState();
    /**
     * <code>string newState = 2;</code>
     * @return The bytes for newState.
     */
    com.google.protobuf.ByteString
        getNewStateBytes();
  }
  /**
   * Protobuf type {@code pb.ValidateMoveReq}
   */
  public static final class ValidateMoveReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ValidateMoveReq)
      ValidateMoveReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidateMoveReq.newBuilder() to construct.
    private ValidateMoveReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateMoveReq() {
      oldState_ = "";
      newState_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidateMoveReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidateMoveReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              oldState_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              newState_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.class, com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.Builder.class);
    }

    public static final int OLDSTATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object oldState_;
    /**
     * <code>string oldState = 1;</code>
     * @return The oldState.
     */
    @java.lang.Override
    public java.lang.String getOldState() {
      java.lang.Object ref = oldState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldState_ = s;
        return s;
      }
    }
    /**
     * <code>string oldState = 1;</code>
     * @return The bytes for oldState.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOldStateBytes() {
      java.lang.Object ref = oldState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEWSTATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object newState_;
    /**
     * <code>string newState = 2;</code>
     * @return The newState.
     */
    @java.lang.Override
    public java.lang.String getNewState() {
      java.lang.Object ref = newState_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newState_ = s;
        return s;
      }
    }
    /**
     * <code>string newState = 2;</code>
     * @return The bytes for newState.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNewStateBytes() {
      java.lang.Object ref = newState_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOldStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldState_);
      }
      if (!getNewStateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newState_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOldStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oldState_);
      }
      if (!getNewStateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq)) {
        return super.equals(obj);
      }
      com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq other = (com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq) obj;

      if (!getOldState()
          .equals(other.getOldState())) return false;
      if (!getNewState()
          .equals(other.getNewState())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OLDSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getOldState().hashCode();
      hash = (37 * hash) + NEWSTATE_FIELD_NUMBER;
      hash = (53 * hash) + getNewState().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ValidateMoveReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ValidateMoveReq)
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.class, com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.Builder.class);
      }

      // Construct using com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        oldState_ = "";

        newState_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveReq_descriptor;
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq getDefaultInstanceForType() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq build() {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq buildPartial() {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq result = new com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq(this);
        result.oldState_ = oldState_;
        result.newState_ = newState_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq) {
          return mergeFrom((com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq other) {
        if (other == com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq.getDefaultInstance()) return this;
        if (!other.getOldState().isEmpty()) {
          oldState_ = other.oldState_;
          onChanged();
        }
        if (!other.getNewState().isEmpty()) {
          newState_ = other.newState_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object oldState_ = "";
      /**
       * <code>string oldState = 1;</code>
       * @return The oldState.
       */
      public java.lang.String getOldState() {
        java.lang.Object ref = oldState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string oldState = 1;</code>
       * @return The bytes for oldState.
       */
      public com.google.protobuf.ByteString
          getOldStateBytes() {
        java.lang.Object ref = oldState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string oldState = 1;</code>
       * @param value The oldState to set.
       * @return This builder for chaining.
       */
      public Builder setOldState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string oldState = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldState() {
        
        oldState_ = getDefaultInstance().getOldState();
        onChanged();
        return this;
      }
      /**
       * <code>string oldState = 1;</code>
       * @param value The bytes for oldState to set.
       * @return This builder for chaining.
       */
      public Builder setOldStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldState_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object newState_ = "";
      /**
       * <code>string newState = 2;</code>
       * @return The newState.
       */
      public java.lang.String getNewState() {
        java.lang.Object ref = newState_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          newState_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string newState = 2;</code>
       * @return The bytes for newState.
       */
      public com.google.protobuf.ByteString
          getNewStateBytes() {
        java.lang.Object ref = newState_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newState_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string newState = 2;</code>
       * @param value The newState to set.
       * @return This builder for chaining.
       */
      public Builder setNewState(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        newState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string newState = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewState() {
        
        newState_ = getDefaultInstance().getNewState();
        onChanged();
        return this;
      }
      /**
       * <code>string newState = 2;</code>
       * @param value The bytes for newState to set.
       * @return This builder for chaining.
       */
      public Builder setNewStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        newState_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ValidateMoveReq)
    }

    // @@protoc_insertion_point(class_scope:pb.ValidateMoveReq)
    private static final com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq();
    }

    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateMoveReq>
        PARSER = new com.google.protobuf.AbstractParser<ValidateMoveReq>() {
      @java.lang.Override
      public ValidateMoveReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidateMoveReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidateMoveReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateMoveReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidateMoveRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.ValidateMoveResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool valid = 1;</code>
     * @return The valid.
     */
    boolean getValid();
  }
  /**
   * Protobuf type {@code pb.ValidateMoveResp}
   */
  public static final class ValidateMoveResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.ValidateMoveResp)
      ValidateMoveRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidateMoveResp.newBuilder() to construct.
    private ValidateMoveResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidateMoveResp() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidateMoveResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidateMoveResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              valid_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.class, com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.Builder.class);
    }

    public static final int VALID_FIELD_NUMBER = 1;
    private boolean valid_;
    /**
     * <code>bool valid = 1;</code>
     * @return The valid.
     */
    @java.lang.Override
    public boolean getValid() {
      return valid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valid_ != false) {
        output.writeBool(1, valid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, valid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp)) {
        return super.equals(obj);
      }
      com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp other = (com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp) obj;

      if (getValid()
          != other.getValid()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getValid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.ValidateMoveResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.ValidateMoveResp)
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.class, com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.Builder.class);
      }

      // Construct using com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        valid_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.internal_static_pb_ValidateMoveResp_descriptor;
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp getDefaultInstanceForType() {
        return com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp build() {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp buildPartial() {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp result = new com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp(this);
        result.valid_ = valid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp) {
          return mergeFrom((com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp other) {
        if (other == com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp.getDefaultInstance()) return this;
        if (other.getValid() != false) {
          setValid(other.getValid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean valid_ ;
      /**
       * <code>bool valid = 1;</code>
       * @return The valid.
       */
      @java.lang.Override
      public boolean getValid() {
        return valid_;
      }
      /**
       * <code>bool valid = 1;</code>
       * @param value The valid to set.
       * @return This builder for chaining.
       */
      public Builder setValid(boolean value) {
        
        valid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool valid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValid() {
        
        valid_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.ValidateMoveResp)
    }

    // @@protoc_insertion_point(class_scope:pb.ValidateMoveResp)
    private static final com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp();
    }

    public static com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidateMoveResp>
        PARSER = new com.google.protobuf.AbstractParser<ValidateMoveResp>() {
      @java.lang.Override
      public ValidateMoveResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidateMoveResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidateMoveResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidateMoveResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.chesshouzs.server.service.rpc.pb.MatchServiceModel.ValidateMoveResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ValidateMoveReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ValidateMoveReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ValidateMoveResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_ValidateMoveResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031match_service_model.proto\022\002pb\"5\n\017Valid" +
      "ateMoveReq\022\020\n\010oldState\030\001 \001(\t\022\020\n\010newState" +
      "\030\002 \001(\t\"!\n\020ValidateMoveResp\022\r\n\005valid\030\001 \001(" +
      "\010B&\n$com.chesshouzs.server.service.rpc.p" +
      "bb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_ValidateMoveReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_ValidateMoveReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ValidateMoveReq_descriptor,
        new java.lang.String[] { "OldState", "NewState", });
    internal_static_pb_ValidateMoveResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_ValidateMoveResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_ValidateMoveResp_descriptor,
        new java.lang.String[] { "Valid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
