// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: match_service.proto

package com.chesshouzs.server.service.rpc.pb;

public final class MatchServiceOuterClass {
  private MatchServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023match_service.proto\022\002pb\032\031match_service" +
      "_model.proto2I\n\014MatchService\0229\n\014Validate" +
      "Move\022\023.pb.ValidateMoveReq\032\024.pb.ValidateM" +
      "oveRespB&\n$com.chesshouzs.server.service" +
      ".rpc.pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chesshouzs.server.service.rpc.pb.MatchServiceModel.getDescriptor(),
        });
    com.chesshouzs.server.service.rpc.pb.MatchServiceModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
